# Generated by Django 5.2.8 on 2025-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(max_length=5000)),
                ('image', models.FileField(upload_to='images')),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('time', models.CharField()),
                ('rejissyor', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
